// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// log_llh_ind
double log_llh_ind(bool variability_hetero, arma::rowvec Otime_i, arma::vec Wtime_i, arma::mat Os_i, arma::mat Ws_i, arma::vec omega, arma::mat b_om, List nb_points_int, double alpha_sigma, bool left_trunc, arma::mat Os_0_i, arma::mat Ws_0_i, bool competing_risk, double alpha_sigma_CR, arma::vec beta, arma::rowvec Xtime_i, arma::vec Utime_i, arma::mat b_al, arma::mat Xs_i, arma::mat Us_i, arma::mat Xs_0_i, arma::mat Us_0_i, double alpha_current, arma::vec sharedtype, arma::vec sharedtype_CR, double alpha_current_CR, arma::vec beta_slope, arma::rowvec Xslope_i, arma::mat b_al_slope, arma::vec Uslope_i, arma::mat Xs_slope_i, arma::mat Us_slope_i, arma::mat Xs_slope_0_i, arma::mat Us_slope_0_i, double alpha_slope, double alpha_slope_CR, List HB, arma::vec wk, double Time_i, arma::vec st_i, arma::vec st_0_i, double shape, arma::vec gamma, arma::vec B_i, arma::mat Bs_i, arma::mat Bs_0_i, arma::rowvec Z_i, arma::vec alpha, double P_i, double P_0_i, double shape_CR, arma::vec gamma_CR, arma::vec B_i_CR, arma::mat Bs_i_CR, arma::mat Bs_0_i_CR, arma::rowvec Z_i_CR, arma::vec alpha_CR, arma::mat X_base_i, arma::mat O_base_i, arma::mat W_base_i, arma::mat U_i, arma::vec y_i, int n_row_X, double sigma_epsilon, List event);
RcppExport SEXP _FlexVarJM_log_llh_ind(SEXP variability_heteroSEXP, SEXP Otime_iSEXP, SEXP Wtime_iSEXP, SEXP Os_iSEXP, SEXP Ws_iSEXP, SEXP omegaSEXP, SEXP b_omSEXP, SEXP nb_points_intSEXP, SEXP alpha_sigmaSEXP, SEXP left_truncSEXP, SEXP Os_0_iSEXP, SEXP Ws_0_iSEXP, SEXP competing_riskSEXP, SEXP alpha_sigma_CRSEXP, SEXP betaSEXP, SEXP Xtime_iSEXP, SEXP Utime_iSEXP, SEXP b_alSEXP, SEXP Xs_iSEXP, SEXP Us_iSEXP, SEXP Xs_0_iSEXP, SEXP Us_0_iSEXP, SEXP alpha_currentSEXP, SEXP sharedtypeSEXP, SEXP sharedtype_CRSEXP, SEXP alpha_current_CRSEXP, SEXP beta_slopeSEXP, SEXP Xslope_iSEXP, SEXP b_al_slopeSEXP, SEXP Uslope_iSEXP, SEXP Xs_slope_iSEXP, SEXP Us_slope_iSEXP, SEXP Xs_slope_0_iSEXP, SEXP Us_slope_0_iSEXP, SEXP alpha_slopeSEXP, SEXP alpha_slope_CRSEXP, SEXP HBSEXP, SEXP wkSEXP, SEXP Time_iSEXP, SEXP st_iSEXP, SEXP st_0_iSEXP, SEXP shapeSEXP, SEXP gammaSEXP, SEXP B_iSEXP, SEXP Bs_iSEXP, SEXP Bs_0_iSEXP, SEXP Z_iSEXP, SEXP alphaSEXP, SEXP P_iSEXP, SEXP P_0_iSEXP, SEXP shape_CRSEXP, SEXP gamma_CRSEXP, SEXP B_i_CRSEXP, SEXP Bs_i_CRSEXP, SEXP Bs_0_i_CRSEXP, SEXP Z_i_CRSEXP, SEXP alpha_CRSEXP, SEXP X_base_iSEXP, SEXP O_base_iSEXP, SEXP W_base_iSEXP, SEXP U_iSEXP, SEXP y_iSEXP, SEXP n_row_XSEXP, SEXP sigma_epsilonSEXP, SEXP eventSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type variability_hetero(variability_heteroSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type Otime_i(Otime_iSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Wtime_i(Wtime_iSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Os_i(Os_iSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ws_i(Ws_iSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type b_om(b_omSEXP);
    Rcpp::traits::input_parameter< List >::type nb_points_int(nb_points_intSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_sigma(alpha_sigmaSEXP);
    Rcpp::traits::input_parameter< bool >::type left_trunc(left_truncSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Os_0_i(Os_0_iSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ws_0_i(Ws_0_iSEXP);
    Rcpp::traits::input_parameter< bool >::type competing_risk(competing_riskSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_sigma_CR(alpha_sigma_CRSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type Xtime_i(Xtime_iSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Utime_i(Utime_iSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type b_al(b_alSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Xs_i(Xs_iSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Us_i(Us_iSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Xs_0_i(Xs_0_iSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Us_0_i(Us_0_iSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_current(alpha_currentSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sharedtype(sharedtypeSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sharedtype_CR(sharedtype_CRSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_current_CR(alpha_current_CRSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta_slope(beta_slopeSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type Xslope_i(Xslope_iSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type b_al_slope(b_al_slopeSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Uslope_i(Uslope_iSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Xs_slope_i(Xs_slope_iSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Us_slope_i(Us_slope_iSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Xs_slope_0_i(Xs_slope_0_iSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Us_slope_0_i(Us_slope_0_iSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_slope(alpha_slopeSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_slope_CR(alpha_slope_CRSEXP);
    Rcpp::traits::input_parameter< List >::type HB(HBSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type wk(wkSEXP);
    Rcpp::traits::input_parameter< double >::type Time_i(Time_iSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type st_i(st_iSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type st_0_i(st_0_iSEXP);
    Rcpp::traits::input_parameter< double >::type shape(shapeSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type B_i(B_iSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Bs_i(Bs_iSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Bs_0_i(Bs_0_iSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type Z_i(Z_iSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type P_i(P_iSEXP);
    Rcpp::traits::input_parameter< double >::type P_0_i(P_0_iSEXP);
    Rcpp::traits::input_parameter< double >::type shape_CR(shape_CRSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type gamma_CR(gamma_CRSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type B_i_CR(B_i_CRSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Bs_i_CR(Bs_i_CRSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Bs_0_i_CR(Bs_0_i_CRSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type Z_i_CR(Z_i_CRSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type alpha_CR(alpha_CRSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X_base_i(X_base_iSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type O_base_i(O_base_iSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type W_base_i(W_base_iSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type U_i(U_iSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y_i(y_iSEXP);
    Rcpp::traits::input_parameter< int >::type n_row_X(n_row_XSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_epsilon(sigma_epsilonSEXP);
    Rcpp::traits::input_parameter< List >::type event(eventSEXP);
    rcpp_result_gen = Rcpp::wrap(log_llh_ind(variability_hetero, Otime_i, Wtime_i, Os_i, Ws_i, omega, b_om, nb_points_int, alpha_sigma, left_trunc, Os_0_i, Ws_0_i, competing_risk, alpha_sigma_CR, beta, Xtime_i, Utime_i, b_al, Xs_i, Us_i, Xs_0_i, Us_0_i, alpha_current, sharedtype, sharedtype_CR, alpha_current_CR, beta_slope, Xslope_i, b_al_slope, Uslope_i, Xs_slope_i, Us_slope_i, Xs_slope_0_i, Us_slope_0_i, alpha_slope, alpha_slope_CR, HB, wk, Time_i, st_i, st_0_i, shape, gamma, B_i, Bs_i, Bs_0_i, Z_i, alpha, P_i, P_0_i, shape_CR, gamma_CR, B_i_CR, Bs_i_CR, Bs_0_i_CR, Z_i_CR, alpha_CR, X_base_i, O_base_i, W_base_i, U_i, y_i, n_row_X, sigma_epsilon, event));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_FlexVarJM_log_llh_ind", (DL_FUNC) &_FlexVarJM_log_llh_ind, 65},
    {NULL, NULL, 0}
};

RcppExport void R_init_FlexVarJM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
